### ISSUE TITLE
1.10.14 tag is missing changes from 1.10.13

### ISSUE THREAD

**Issue by kwojcik** [jfromaniello/selfsigned#52]
I think that the wrong commit is tagged with 1.10.14. It does not contain the changes in 1.10.13, notably the node-forge version change

**Comment by drjauss** [comment]
Any update about this? @jfromaniello

**Comment by jfromaniello** [comment]
Hi folks, `1.10.14` is the same than `1.10.12`, I had to patch it again because the upgrade of node-forge in 1.10.13 breaked compatibility with node 8.

I released a major change, `2.0.0` which is the same than `1.10.13`, it upgrades node-forge to the non vulnerable version and it also adds a node.js engine constraint.

Sorry about all this confusion but it seems a reasonable approach..

I wrote about this here: https://github.com/jfromaniello/selfsigned/issues/50#issuecomment-1010010700
